import path from 'path'; 
import { test, expect } from '@playwright/test';
test.use({
  viewport: {
    height: 1080,
    width: 1920
  }
});

test('test', async ({ page }) => {
  await page.goto('https://kingfisher-btcprod.vercel.app/');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).click();
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).click();
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).fill('smaling.kingfisher@icloud.como');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('Tab');
  await page.getByRole('button', { name: 'Wachtwoord vergeten?' }).press('Tab');
  await page.getByRole('textbox', { name: 'Minimaal 6 tekens' }).fill('test123!');
  await page.getByRole('textbox', { name: 'Minimaal 6 tekens' }).press('Enter');
  await page.getByRole('button', { name: 'Inloggen' }).click();
  await page.getByRole('textbox', { name: 'Minimaal 6 tekens' }).click();
  await page.getByRole('textbox', { name: 'Minimaal 6 tekens' }).click();
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).click();
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).click();
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'naam@kingfisher.nl' }).fill('smaling.kingfisher@icloud.com');
  await page.getByRole('button', { name: 'Inloggen' }).click();
  await page.getByRole('button', { name: /actief canvas/i }).click();
  await page.getByRole('button', { name: 'Nieuw canvas' }).click();
  await page.getByRole('button', { name: 'Actief canvas Canvas 21 apr' }).click();
  await page.getByRole('button', { name: 'Canvas 21 apr 2026 Aangemaakt' }).first().click();
  await page.getByRole('button', { name: 'Dossier' }).click();
  await page.getByText('Bestanden toevoegen aan').click();
  await page.setInputFiles('input[type="file"]', path.join(__dirname, 'assets', 'Work in progress BTP MAG Final Version-1.pptx'));  await page.locator('div').filter({ hasText: 'Bestanden toevoegen aan' }).nth(4).click();
  await page.locator('input[type="file"]').setInputFiles('./strategie_text.txt');
await page.locator('input[type="file"]').setInputFiles(path.join(__dirname, 'assets', 'strategie_text.txt'));  await page.getByText('MissieVisieAmbitieKernwaardenDoelstellingenSWOT').click();
  await page.getByRole('button', { name: 'Magic Staff — AI voorstel op' }).first().click();
  await page.getByRole('button', { name: 'Magic Staff — AI voorstel op' }).nth(1).click();
  await page.getByRole('button', { name: 'Magic Staff — AI voorstel op' }).nth(2).click();
  await page.getByRole('button', { name: 'Magic Staff — AI voorstel op' }).nth(3).click();
  await page.getByRole('button', { name: 'Magic Staff — AI voorstel op' }).nth(5).click();
  await page.getByText('🌐 Algemene kennis — 9 items· geen Dossier gevondenAlle toevoegenWeggooien').click();
  await page.getByRole('button', { name: 'Alle toevoegen' }).click();
  await page.locator('.space-y-6.pb-6 > .grid > div:nth-child(2) > .flex.items-center.justify-between > .flex').click();
  await page.getByRole('button', { name: 'Niet relevant' }).first().click();
  await page.getByRole('button', { name: 'Kans' }).click();
  await page.getByRole('button', { name: 'Niet relevant' }).first().click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Bedreiging' }).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Bedreiging' }).nth(1).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Bedreiging' }).nth(2).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Kans' }).nth(1).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Bedreiging' }).nth(3).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Bedreiging' }).nth(4).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Kans' }).nth(2).click();
  await page.getByRole('button', { name: 'Alle toevoegen' }).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Sterkte' }).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Sterkte' }).nth(1).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Zwakte' }).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Zwakte' }).nth(1).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(1).click();
  await page.getByRole('button', { name: 'Zwakte' }).nth(2).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(4).click();
  await page.getByRole('button', { name: 'Sterkte' }).nth(2).click();
  await page.getByRole('button', { name: 'Niet relevant' }).nth(4).click();
  await page.getByRole('button', { name: 'Sterkte' }).nth(3).click();
  await page.locator('div:nth-child(2) > .space-y-1\\.5 > div:nth-child(6) > .flex > .opacity-0').click();
  await page.locator('div:nth-child(2) > .space-y-1\\.5 > div:nth-child(6) > .flex > .opacity-0').click();
  await page.locator('.group.flex.items-start.gap-2.border-l-4.rounded-r-lg.px-4.py-3.bg-white.shadow-sm.border-l-slate-200 > .flex > .opacity-0').first().click();
  await page.getByRole('button', { name: 'Genereer Thema\'s' }).click();
  await page.getByRole('button', { name: '×' }).first().click();
  await page.getByText('AI en automatisering').click();
  await page.getByText('AI en automatisering').click();
  await page.getByRole('button', { name: 'Alle toevoegen' }).click();
  await page.getByRole('button', { name: 'Alles toevoegen' }).click();
  await page.locator('div:nth-child(2) > .flex.items-center.gap-3 > .text-slate-400').click();
  await page.getByRole('button', { name: 'Alles toevoegen' }).click();
  await page.locator('div:nth-child(3) > .flex.items-center.gap-3 > .text-slate-400').click();
  await page.getByRole('button', { name: 'Alles toevoegen' }).click();
  await page.locator('div:nth-child(4) > .flex.items-center.gap-3 > .text-slate-400').click();
  await page.getByRole('button', { name: 'Alles toevoegen' }).click();
  await page.locator('div:nth-child(5) > .flex.items-center.gap-3 > .text-slate-400').click();
  await page.getByRole('button', { name: 'Alles toevoegen' }).click();
  await page.locator('div:nth-child(6) > .flex.items-center.gap-3 > .text-slate-400').click();
  await page.getByRole('button', { name: 'Alles toevoegen' }).click();
  await page.getByRole('button', { name: 'Magic Staff — AI voorstel op' }).nth(4).click();
  await page.getByRole('button', { name: 'Magic Staff — AI voorstel op' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Waarom bestaan wij?' }).click();
  await page.getByRole('textbox', { name: 'Waarom bestaan wij?' }).fill('wij zorgen voor life time employment');
  await page.getByRole('textbox', { name: 'Waar staan wij over 5 jaar?' }).click();
  await page.getByRole('textbox', { name: 'Onze grote, haast onmogelijke' }).click();
  await page.getByRole('textbox', { name: 'Onze grote, haast onmogelijke' }).fill('meest innovatieve digitale consulatncy firm');
  await page.getByRole('textbox', { name: '+ Waarde…' }).click();
  await page.getByRole('textbox', { name: '+ Waarde…' }).fill('mens op 1');
  await page.getByRole('textbox', { name: '+ Waarde…' }).press('Enter');
  await page.getByRole('textbox', { name: '+ Waarde…' }).fill('mens op 1');
  await page.getByRole('textbox', { name: '+ Waarde…' }).press('Enter');
  await page.locator('div').filter({ hasText: /^Kernwaarden$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Kernwaarden$/ }).nth(1).click();
  await page.getByRole('textbox', { name: '+ Waarde…' }).click();
  await page.locator('.flex.flex-wrap.gap-1\\.5').click();
  await page.getByRole('textbox', { name: '+ Waarde…' }).click();
  await page.getByRole('textbox', { name: '+ Waarde…' }).fill('waarom kan ik dit niet invulle');
  await page.getByRole('textbox', { name: '+ Waarde…' }).press('Enter');
  await page.getByRole('textbox', { name: 'Waar staan wij over 5 jaar?' }).click();
  await page.getByRole('textbox', { name: 'Waar staan wij over 5 jaar?' }).fill('test visie voor over 5 jaar');
  await page.getByRole('button', { name: '✨ Improve' }).nth(2).click();
  await page.locator('.fixed.inset-0.z-40').click();
  await page.getByRole('button', { name: 'Strategisch Advies' }).click();
  await page.getByRole('button', { name: 'Analyseer strategie' }).click();
  await page.locator('div:nth-child(2) > .text-white\\/40').click();
  await page.getByRole('button', { name: 'Strategie Rapport' }).click();
  await page.getByRole('button', { name: 'Advies in print' }).click();
  await page.getByRole('button', { name: 'Advies in print ✓' }).click();
  await page.getByRole('button', { name: 'Advies in print ✓' }).click();
  await page.locator('div').filter({ hasText: 'Kingfisher & PartnersStrategie OverzichtCanvas 21 apr 2026Business' }).nth(5).click();
  await page.getByRole('button', { name: 'SWOT Analyse' }).click();
  await page.getByRole('button', { name: 'Advies in print' }).click();
  await page.getByRole('button', { name: 'Advies in print' }).click();
  await page.getByRole('button', { name: 'Balanced Scorecard' }).click();
  await page.getByRole('button', { name: 'Advies in print' }).click();
  await page.getByRole('button', { name: 'Advies in print' }).click();
  await page.getByRole('button', { name: 'PDF / Printen' }).click();
  await page.locator('div:nth-child(2) > .text-white\\/40.hover\\:text-white').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByText('Leidende principesKlik om het').click();
  await page.goto('about:blank');
});